import {
  ArcElement,
  BarElement,
  CategoryScale,
  Chart as ChartJS,
  Legend,
  LinearScale,
  Title,
  Tooltip,
} from "chart.js";
import { DollarSign, TrendingUp, Users } from "lucide-react";
import { Bar, Pie } from "react-chartjs-2";

// Register Chart.js components
ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, ArcElement);

// Data for Monthly Revenue, User Growth, and Analytics
const stats = [
  {
    title: "Total Revenue",
    value: "120,000 DT", // Changed USD to DT
    icon: <DollarSign className="w-6 h-6 text-green-500" />,
    description:
      "This metric tracks the total revenue generated by the platform. A significant indicator of the business's financial health and growth. Revenue growth indicates strong user engagement and increased service usage.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Monthly Revenue",
          data: [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000],
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          borderColor: "rgba(54, 162, 235, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
  {
    title: "Total Users",
    value: "50,000",
    icon: <Users className="w-6 h-6 text-blue-500" />,
    description:
      "This number represents the total users currently active on the platform. A key metric for assessing the reach and popularity of the platform. High user numbers are often correlated with platform success and market penetration.",
    pieCharts: [
      {
        title: "Age Distribution",
        data: [10, 15, 25, 30, 20], // Example data: percentage of users in each age range
        labels: ["18-24", "25-34", "35-44", "45-54", "55+"],
        backgroundColor: [
          "rgba(75, 192, 192, 0.6)",
          "rgba(255, 159, 64, 0.6)",
          "rgba(54, 162, 235, 0.6)",
          "rgba(153, 102, 255, 0.6)",
          "rgba(255, 99, 132, 0.6)",
        ],
      },
      {
        title: "Gender Distribution",
        data: [40, 30, 30], // Example data: percentage of male, female, and not specified
        labels: ["Male", "Female", "Not Specified"],
        backgroundColor: [
          "rgba(54, 162, 235, 0.6)",  // Blue
          "rgba(255, 99, 132, 0.6)",  // Red
          "rgba(201, 203, 207, 0.6)", // Grey
        ],
      },
    ],
  },
  {
    title: "Active Users",
    value: "40,000",
    icon: <Users className="w-6 h-6 text-purple-500" />,
    description:
      "Active Users refers to the number of users who engage with the platform regularly. This metric reflects the retention of users and the effectiveness of platform features in driving consistent engagement.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Active Users",
          data: [800, 900, 1000, 1100, 1200, 1500, 1700, 2000, 2300, 2700, 3100, 3500],
          backgroundColor: "rgba(75, 192, 192, 0.6)",
          borderColor: "rgba(75, 192, 192, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
  {
    title: "Growth Rate",
    value: "+8.5%",
    icon: <TrendingUp className="w-6 h-6 text-orange-500" />,
    description:
      "The growth rate is the percentage increase in key metrics (revenue, users, active users) compared to the previous month. A high growth rate signals an expanding user base, improving engagement, or an increase in sales.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Growth Rate",
          data: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24],
          backgroundColor: "rgba(153, 102, 255, 0.6)",
          borderColor: "rgba(153, 102, 255, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
];

const InsightsSection = () => {
  return (
    <div className="w-full py-6">
      <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">
        Insights & Analytics
      </h2>

      {/* Insights Sections - Each Section for Different Metric */}
      <div className="w-full space-y-10">
        {stats.map((stat, index) => (
          <div key={index} className="w-full border-b border-gray-200 pb-8 mb-8">
            <div className="flex items-center justify-center mb-4">
              <div className="flex items-center">
                {stat.icon}
                <div className="text-xl font-semibold ml-2 text-gray-800">
                  {stat.title}
                </div>
              </div>
            </div>

            <div className="mt-2 text-3xl font-bold text-gray-900 text-center">
              {stat.value}
            </div>

            <div className="mt-4 text-sm text-gray-700 text-center max-w-2xl mx-auto">
              {stat.description}
            </div>

            {/* Charts Section - improved width handling */}
            <div className="mt-8 w-full">
              {stat.chartData && (
                <div className="w-full h-[300px]">
                  <Bar
                    data={stat.chartData}
                    options={{
                      responsive: true,
                      maintainAspectRatio: false,
                      plugins: {
                        legend: {
                          position: "top",
                        },
                        tooltip: {
                          backgroundColor: "#333",
                          titleColor: "#fff",
                          bodyColor: "#fff",
                        },
                      },
                      scales: {
                        x: {
                          ticks: {
                            color: "#555",
                          },
                          grid: {
                            color: "rgba(0,0,0,0.05)",
                          },
                        },
                        y: {
                          ticks: {
                            color: "#555",
                          },
                          grid: {
                            color: "rgba(0,0,0,0.05)",
                          },
                        },
                      },
                    }}
                  />
                </div>
              )}

              {/* Pie Charts with better responsiveness */}
              {stat.pieCharts && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8 w-full">
                  {stat.pieCharts.map((chart, idx) => (
                    <div key={idx} className="w-full h-[300px]">
                      <h3 className="text-lg font-semibold text-gray-800 text-center mb-4">
                        {chart.title}
                      </h3>
                      <Pie
                        data={{
                          labels: chart.labels,
                          datasets: [
                            {
                              data: chart.data,
                              backgroundColor: chart.backgroundColor,
                            },
                          ],
                        }}
                        options={{
                          responsive: true,
                          maintainAspectRatio: false,
                          plugins: {
                            legend: {
                              position: "bottom",
                              labels: {
                                padding: 16,
                              },
                            },
                            tooltip: {
                              backgroundColor: "#333",
                              titleColor: "#fff",
                              bodyColor: "#fff",
                            },
                          },
                        }}
                      />
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default InsightsSection;
