import React from "react";
import { DollarSign, Users, TrendingUp } from "lucide-react";
import { Bar, Pie } from "react-chartjs-2";
import {
  Chart as ChartJS,
  Title,
  Tooltip,
  Legend,
  BarElement,
  CategoryScale,
  LinearScale,
  ArcElement, // Needed for Pie chart
} from "chart.js";

// Register Chart.js components
ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, ArcElement);

// Data for Monthly Revenue, User Growth, and Analytics
const stats = [
  {
    title: "Total Revenue",
    value: "120,000 DT", // Changed USD to DT
    icon: <DollarSign className="w-6 h-6 text-green-500" />,
    description:
      "This metric tracks the total revenue generated by the platform. A significant indicator of the business's financial health and growth. Revenue growth indicates strong user engagement and increased service usage.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Monthly Revenue",
          data: [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000],
          backgroundColor: "rgba(54, 162, 235, 0.6)",
          borderColor: "rgba(54, 162, 235, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
  {
    title: "Total Users",
    value: "50,000",
    icon: <Users className="w-6 h-6 text-blue-500" />,
    description:
      "This number represents the total users currently active on the platform. A key metric for assessing the reach and popularity of the platform. High user numbers are often correlated with platform success and market penetration.",
    pieCharts: [
      {
        title: "Age Distribution",
        data: [10, 15, 25, 30, 20], // Example data: percentage of users in each age range
        labels: ["18-24", "25-34", "35-44", "45-54", "55+"],
        backgroundColor: [
          "rgba(75, 192, 192, 0.6)",
          "rgba(255, 159, 64, 0.6)",
          "rgba(54, 162, 235, 0.6)",
          "rgba(153, 102, 255, 0.6)",
          "rgba(255, 99, 132, 0.6)",
        ],
      },
      {
        title: "Gender Distribution",
        data: [40, 30, 30], // Example data: percentage of male, female, and not specified
        labels: ["Male", "Female", "Not Specified"],
        backgroundColor: [
          "rgba(54, 162, 235, 0.6)",  // Blue
          "rgba(255, 99, 132, 0.6)",  // Red
          "rgba(201, 203, 207, 0.6)", // Grey
        ],
      },
    ],
  },
  {
    title: "Active Users",
    value: "40,000",
    icon: <Users className="w-6 h-6 text-purple-500" />,
    description:
      "Active Users refers to the number of users who engage with the platform regularly. This metric reflects the retention of users and the effectiveness of platform features in driving consistent engagement.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Active Users",
          data: [800, 900, 1000, 1100, 1200, 1500, 1700, 2000, 2300, 2700, 3100, 3500],
          backgroundColor: "rgba(75, 192, 192, 0.6)",
          borderColor: "rgba(75, 192, 192, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
  {
    title: "Growth Rate",
    value: "+8.5%",
    icon: <TrendingUp className="w-6 h-6 text-orange-500" />,
    description:
      "The growth rate is the percentage increase in key metrics (revenue, users, active users) compared to the previous month. A high growth rate signals an expanding user base, improving engagement, or an increase in sales.",
    chartData: {
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      datasets: [
        {
          label: "Growth Rate",
          data: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24],
          backgroundColor: "rgba(153, 102, 255, 0.6)",
          borderColor: "rgba(153, 102, 255, 1)",
          borderWidth: 1,
          barThickness: 20,
          borderRadius: 5,
        },
      ],
    },
  },
];

const InsightsSection = () => {
  return (
    <div className="w-full min-h-screen flex flex-col items-center px-6 py-8 bg-white">
      <h2 className="text-3xl font-extrabold text-gray-900 mb-10 text-center">
        Insights & Analytics
      </h2>

      {/* Insights Sections - Each Section for Different Metric */}
      <div className="w-full space-y-10">
        {stats.map((stat, index) => (
          <div key={index} className="w-full border-b border-gray-300 pb-6 mb-10">
            <div className="flex items-center justify-center mb-4">
              <div className="flex items-center">
                {stat.icon}
                <div className="text-xl font-semibold ml-2 text-gray-900 text-center">
                  {stat.title}
                </div>
              </div>
            </div>

            <div className="mt-2 text-3xl font-bold text-gray-900 text-center">
              {stat.value}
            </div>

            <div className="mt-4 text-sm text-gray-700 text-center">{stat.description}</div>

            {/* Bar Chart for each metric */}
            <div className="w-full h-[350px] mt-6 flex justify-center mb-10">
              {stat.chartData && (
                <Bar
                  data={stat.chartData}
                  options={{
                    responsive: true,
                    plugins: {
                      legend: {
                        position: "top",
                      },
                      tooltip: {
                        backgroundColor: "#333",
                        titleColor: "#fff",
                        bodyColor: "#fff",
                      },
                    },
                    scales: {
                      x: {
                        ticks: {
                          color: "#555",
                        },
                        grid: {
                          color: "rgba(0,0,0,0.1)",
                        },
                      },
                      y: {
                        ticks: {
                          color: "#555",
                        },
                        grid: {
                          color: "rgba(0,0,0,0.1)",
                        },
                      },
                    },
                  }}
                />
              )}
              {/* Pie Charts for Users (Age and Gender) */}
              {stat.pieCharts && stat.pieCharts.map((chart, idx) => (
                <div key={idx} className="w-[350px] h-[350px] mt-6 flex justify-center items-center mb-10">
                  <div className="w-full text-center">
                    <h3 className="text-xl font-semibold text-gray-900">{chart.title}</h3>
                    <Pie
                      data={{
                        labels: chart.labels,
                        datasets: [
                          {
                            data: chart.data,
                            backgroundColor: chart.backgroundColor,
                          },
                        ],
                      }}
                      options={{
                        responsive: true,
                        plugins: {
                          legend: {
                            position: "top",
                          },
                          tooltip: {
                            backgroundColor: "#333",
                            titleColor: "#fff",
                            bodyColor: "#fff",
                          },
                        },
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default InsightsSection;
